### ISSUE TITLE
FO3Edit locks Bashed Patch, <#>.esp & hidden error window

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#11]
To reproduce the Issue 
1) Open Gary Bash with a Bashed Patch, <#>.esp that has content (been built at least once with mergers.
2) Open FO3Edit and run with only Bashed Patch, <#>.esp enabled/checked.
3) with FO3Edit still open build the Bashed Patch, <#>.esp with at least one change IE (a tweak change or add/remove a merger)
4) Note Gary Bash should open a error about Bashed Patch, <#>.esp being used by another application or process.

The problem is that this window is very often hidden behind Gary Bash. If possible the window should be flagged always on top. Several times, while patch testing, today I did not see the error window and went on past results that where important.

Perhaps a warning message before rebuilding the Bashed Patch, <#>.esp is possible if FO3Edit is running.

**Comment by valda** [comment]
It's a specification ;)
Please shutdown FO3Edit when rebuild patch.

I think that it is possible to change attribute of error window to topmost.

**Comment by Sativarg** [comment]
You fixed it? Or was it already a specification I missed?

**Comment by valda** [comment]
Not fixed yet.
Because the process of FO3Edit acquired exclusive lock of "Bashed Patch, 0.esp", it's hard to make measures by garybash.
Thanks.

**Comment by Sativarg** [comment]
I had thought A test for "Is running process"
Checking processes running under Windows - comp.lang.python | Google Groups - http://groups.google.com/group/comp.lang.python/browse_thread/thread/1f50065064173ccb?pli=1
List all running processes =
http://tgolden.sc.sabren.com/python/wmi_cookbook.html#running_processes
Then if FO3Edit is running warn user to close FO3Edit before re/building the patch.

**Comment by valda** [comment]
Umm, Because not always only FO3Edit to acquire a exclusive lock of the Bashed Patch, *.esp, that measures seem to be ad-hoc.
I will think about better method.
Thank you for the idea :)

**Comment by Sativarg** [comment]
OK thanks. It is prebably a good idea to try and limit the aplications open when running Gary or Wrye Bash any way.

**Comment by valda** [comment]
Please try c3b4c259766144b354e0b0ed5b582bfff373050d
Fixed that the retry dialog is displayed when failing in the write of bashed patch. 
Thanks.

**Comment by Sativarg** [comment]
Great and with the new feature to export settings its so much easier to make a new patch for each game environment. I have an export with my favorite tweaks that I start with. Great Feature. Probably was Wrye ported but still I'm so glad you imported it.

AH ?Hmm I still don't know how to close an issue...

**Comment by valda** [comment]
Thanks!
I'm glad you like it :)
